name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.3.0'

      - name: Terraform Init
        run: terraform init
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
          YANDEX_CLOUD_ID: ${{ secrets.YANDEX_CLOUD_ID }}
          YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          ADMINS: ${{ secrets.ADMINS }}
          ACCOUNT: ${{ secrets.ACCOUNT }}
          SECRET: ${{ secrets.SECRET }}
          APP_ID: ${{ secrets.APP_ID }}
          TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}

      - name: Terraform Plan
        run: terraform plan
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
          YANDEX_CLOUD_ID: ${{ secrets.YANDEX_CLOUD_ID }}
          YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          ADMINS: ${{ secrets.ADMINS }}
          ACCOUNT: ${{ secrets.ACCOUNT }}
          SECRET: ${{ secrets.SECRET }}
          APP_ID: ${{ secrets.APP_ID }}
          TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
          YANDEX_CLOUD_ID: ${{ secrets.YANDEX_CLOUD_ID }}
          YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          ADMINS: ${{ secrets.ADMINS }}
          ACCOUNT: ${{ secrets.ACCOUNT }}
          SECRET: ${{ secrets.SECRET }}
          APP_ID: ${{ secrets.APP_ID }}
          TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}
```
